images:
  klipper:
    repository: mkuf/klipper
    pullPolicy: IfNotPresent
    tag: ""
  moonraker:
    repository: mkuf/moonraker
    pullPolicy: IfNotPresent
    tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

mcus:
  - name: usb
    hostPath: /dev
    mountPath: /dev

klipperConfig: klipper-config
printerDataName: printer-data

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  privileged: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
